# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atrelease < Formula
  desc "Multi-agent release preparation team for multi-language repositories"
  homepage "https://github.com/agentplexus/agent-team-release"
  version "0.6.0"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentplexus/agent-team-release/releases/download/v0.6.0/agent-team-release_0.6.0_darwin_x86_64.tar.gz"
      sha256 "b7e2b426ab93eb2b6186f0ddd0b2d3bbaa336052052f34b19bfe75d44cc5e24c"

      def install
        bin.install "atrelease"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentplexus/agent-team-release/releases/download/v0.6.0/agent-team-release_0.6.0_darwin_arm64.tar.gz"
      sha256 "bb082e810c1d81105fd361109f752891a0019a56376c6eb06614d8e786ebd91b"

      def install
        bin.install "atrelease"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentplexus/agent-team-release/releases/download/v0.6.0/agent-team-release_0.6.0_linux_x86_64.tar.gz"
      sha256 "726f20066074357c580e89a973f30f5d70973a76254b9c6c6fefed256d605ebd"
      def install
        bin.install "atrelease"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentplexus/agent-team-release/releases/download/v0.6.0/agent-team-release_0.6.0_linux_arm64.tar.gz"
      sha256 "7bbc62ac313b92a0014f20859fbc84241c2f9d1e89b9afc2c7c38b3e306b5d82"
      def install
        bin.install "atrelease"
      end
    end
  end

  test do
    system "#{bin}/atrelease", "version"
  end
end
