# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseAgentTeam < Formula
  desc "Multi-agent release preparation team for multi-language repositories"
  homepage "https://github.com/agentplexus/release-agent-team"
  version "0.5.0"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentplexus/release-agent-team/releases/download/v0.5.0/release-agent-team_0.5.0_darwin_x86_64.tar.gz"
      sha256 "56339e549c1c56ce6de6c4374d06503f51d8141e6d29b4372358271cd9cbd313"

      def install
        bin.install "release-agent-team"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentplexus/release-agent-team/releases/download/v0.5.0/release-agent-team_0.5.0_darwin_arm64.tar.gz"
      sha256 "23eb2b7618f6442877da0bc69ff5d25bcb60b24f5746754858b3eaf1c0067fe0"

      def install
        bin.install "release-agent-team"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentplexus/release-agent-team/releases/download/v0.5.0/release-agent-team_0.5.0_linux_x86_64.tar.gz"
      sha256 "878cf6b56bd5ae41db978dbd6940b7b049bd654cd43b1a627af1484c39f79512"
      def install
        bin.install "release-agent-team"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentplexus/release-agent-team/releases/download/v0.5.0/release-agent-team_0.5.0_linux_arm64.tar.gz"
      sha256 "77cded728510078f6b6a946044d1a25caca2a95b5292f0c604bf561006189a36"
      def install
        bin.install "release-agent-team"
      end
    end
  end

  test do
    system "#{bin}/release-agent-team", "version"
  end
end
